# Generated by Django 5.2.11 on 2026-03-02 14:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_lavagem', models.DateField(blank=True, null=True, verbose_name='Última Lavagem')),
                ('proxima_lavagem', models.DateField(blank=True, null=True, verbose_name='Próxima Lavagem')),
                ('polietileno', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('metade', 'Metade'), ('danificado', 'Danificado')], max_length=20, null=True)),
                ('cones', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=10, null=True)),
                ('localizador', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_funciona', 'Não Funciona')], max_length=20, null=True)),
                ('lona_facil', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=10, null=True)),
                ('step', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=10, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('alta', 'Alta'), ('canguru', 'Canguru'), ('vanderleia', 'Vanderleia')], max_length=20, null=True)),
                ('classificacao', models.CharField(blank=True, choices=[('agregado', 'Agregamento'), ('frota', 'Frota'), ('terceiro', 'Terceiro')], max_length=20, null=True, verbose_name='Classificação')),
                ('situacao', models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('parado', 'Parado')], default='ativo', max_length=20, null=True, verbose_name='Situação')),
                ('local', models.CharField(blank=True, help_text='Atualizado automaticamente por API', max_length=255, null=True, verbose_name='Local')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='carretas/fotos/', verbose_name='Foto')),
                ('documento', models.FileField(blank=True, null=True, upload_to='carretas/documentos/', verbose_name='Documento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carreta',
                'verbose_name_plural': 'Carretas',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_faturamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Meta de Faturamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gestor',
                'verbose_name_plural': 'Gestores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código')),
                ('nome_razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, null=True)),
                ('status', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Status')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('documento', models.FileField(blank=True, null=True, upload_to='proprietarios/documentos/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
                'ordering': ['nome_razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Cavalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('fluxo', models.CharField(blank=True, choices=[('escoria', 'Escória'), ('minerio', 'Minério')], max_length=20, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('bi_truck', 'Bi-truck'), ('toco', 'Toco'), ('trucado', 'Trucado')], max_length=20, null=True, verbose_name='Tipo')),
                ('classificacao', models.CharField(blank=True, choices=[('agregado', 'Agregado'), ('frota', 'Frota'), ('terceiro', 'Terceiro')], max_length=20, null=True, verbose_name='Classificação')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cavalos/fotos/', verbose_name='Foto')),
                ('situacao', models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('parado', 'Parado'), ('desagregado', 'Desagregado')], max_length=20, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='cavalos/documentos/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('carreta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cavalo_acoplado', to='core.carreta', verbose_name='Carreta Agregada')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cavalos', to='core.gestor', verbose_name='Gestor')),
                ('proprietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cavalos', to='core.proprietario', verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Cavalo',
                'verbose_name_plural': 'Cavalos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='LogCarreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acoplamento', 'Acoplamento'), ('desacoplamento', 'Desacoplamento'), ('troca', 'Troca de Carreta'), ('desagregacao', 'Desagregação'), ('motorista_adicionado', 'Motorista Adicionado'), ('motorista_removido', 'Motorista Removido'), ('motorista_alterado', 'Motorista Alterado'), ('proprietario_alterado', 'Proprietário Alterado'), ('troca_proprietario', 'Troca de Proprietário')], max_length=25)),
                ('carreta_anterior', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa Carreta Anterior')),
                ('carreta_nova', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa Carreta Nova')),
                ('motorista_anterior', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motorista Anterior')),
                ('motorista_novo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motorista Novo')),
                ('proprietario_anterior', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proprietário Anterior')),
                ('proprietario_novo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proprietário Novo')),
                ('placa_cavalo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Cavalo')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('cavalo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.cavalo', verbose_name='Cavalo')),
            ],
            options={
                'verbose_name': 'Log de Carreta',
                'verbose_name_plural': 'Logs de Carretas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='motoristas/fotos/', verbose_name='Foto')),
                ('documento', models.FileField(blank=True, null=True, upload_to='motoristas/documentos/', verbose_name='Documento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cavalo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motorista', to='core.cavalo', verbose_name='Cavalo')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CTE', 'CTE'), ('OST', 'OST')], max_length=3, verbose_name='Tipo de Documento')),
                ('filial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Filial')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Série')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento')),
                ('data_documento', models.DateField(blank=True, null=True, verbose_name='Data do Documento')),
                ('motorista', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motorista')),
                ('cavalo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Cavalo')),
                ('carreta', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa da Carreta')),
                ('tipo_frota', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Frota')),
                ('remetente', models.CharField(blank=True, max_length=500, null=True, verbose_name='Remetente')),
                ('destinatario', models.CharField(blank=True, max_length=500, null=True, verbose_name='Destinatário')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal')),
                ('pedagio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Pedágio')),
                ('total_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total do Frete')),
                ('tarifa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tarifa')),
                ('filial_serie_numero', models.CharField(blank=True, max_length=200, null=True, verbose_name='Filial/Série/Número')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.gestor', verbose_name='Gestor')),
            ],
            options={
                'verbose_name': 'Documento de Transporte',
                'verbose_name_plural': 'Documentos de Transporte',
                'ordering': ['-data_documento', '-created_at'],
                'indexes': [models.Index(fields=['tipo_documento', 'filial', 'serie', 'numero_documento'], name='core_docume_tipo_do_f5834f_idx'), models.Index(fields=['data_documento'], name='core_docume_data_do_9bab10_idx'), models.Index(fields=['motorista'], name='core_docume_motoris_2fe774_idx'), models.Index(fields=['cavalo'], name='core_docume_cavalo_47dee2_idx'), models.Index(fields=['gestor'], name='core_docume_gestor__7fccf1_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cavalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_gestores', to='core.cavalo', verbose_name='Cavalo')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.gestor', verbose_name='Gestor')),
            ],
            options={
                'verbose_name': 'Histórico de Gestor',
                'verbose_name_plural': 'Históricos de Gestores',
                'ordering': ['-data_inicio'],
                'indexes': [models.Index(fields=['gestor', 'data_inicio', 'data_fim'], name='core_histor_gestor__d1b003_idx'), models.Index(fields=['cavalo', 'data_inicio', 'data_fim'], name='core_histor_cavalo__be15f4_idx')],
            },
        ),
    ]
