# Generated by Django 5.0 for Filial 16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Carregamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(db_index=True, max_length=44, unique=True, verbose_name='Chave de Acesso')),
                ('serie_nfe', models.CharField(blank=True, max_length=10, verbose_name='Série NFe')),
                ('nota_fiscal', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Nota Fiscal')),
                ('datahora_emissao', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Emissão')),
                ('emit_nome', models.CharField(blank=True, max_length=200, verbose_name='Emitente Nome')),
                ('emit_cnpj', models.CharField(blank=True, db_index=True, max_length=18, verbose_name='Emitente CNPJ')),
                ('dest_nome', models.CharField(blank=True, max_length=200, verbose_name='Destinatário Nome')),
                ('dest_cnpj', models.CharField(blank=True, db_index=True, max_length=18, verbose_name='Destinatário CNPJ')),
                ('xProd_produto', models.CharField(blank=True, max_length=500, verbose_name='Produto (xProd)')),
                ('cfop', models.CharField(blank=True, max_length=10, verbose_name='CFOP')),
                ('qCom_peso', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Peso (qCom)')),
                ('vProd_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor (vProd)')),
                ('modFrete_tomador', models.CharField(blank=True, max_length=100, verbose_name='Modalidade Frete / Tomador')),
                ('nome_cnpj', models.CharField(blank=True, max_length=200, verbose_name='Nome/CNPJ (frete)')),
                ('transp_cnpj', models.CharField(blank=True, max_length=18, verbose_name='Transportadora CNPJ')),
                ('extras', models.JSONField(blank=True, default=dict, help_text='Campos adicionais do XML que variam por fluxo (ex: numero_lacre, codigo_balanca).', verbose_name='Extras')),
                ('fluxo', models.CharField(blank=True, db_index=True, help_text='Ex: Pedágio, Harsco, Bemisa-Usiminas, Bemisa-TCB.', max_length=80, verbose_name='Fluxo de carregamento')),
                ('arquivado', models.BooleanField(db_index=True, default=False, verbose_name='Arquivado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Carregamento',
                'verbose_name_plural': 'Carregamentos',
                'ordering': ['-datahora_emissao', '-criado_em'],
            },
        ),
    ]
