# Generated by Django 5.2.11 on 2026-03-01 14:51

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregamento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='carregamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='Criado em'),
        ),
    ]
