# Generated by Django 5.2.11 on 2026-03-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0002_alter_carregamento_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carregamento',
            options={'ordering': ['criado_em', 'datahora_emissao'], 'verbose_name': 'Carregamento', 'verbose_name_plural': 'Carregamentos'},
        ),
    ]
