# Generated by Django 5.2.11 on 2026-03-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0007_carregamento_ost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ost',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
